### ISSUE TITLE
Where is the NLU_training_dataset folder

### ISSUE THREAD

**Issue by wpwpwpyo** [GaryYufei/PromDA#2]
Sorry to bother you, where is the NLU_training_dataset folder? Does that mean the datasets folder? So,what does the "subj" in "test_path﻿:NLU_training_dataset/subj/test_whole.txt" in the path of "model_config/rt/bert_nlu.yml" mean? There is no "subj" in datasets folder.

**Comment by GaryYufei** [comment]
updated! Thanks for pointing this out.
